import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
# Diubah dari HYPERBOLIC_API_KEY
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") 
BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET")
ALLOWED_USER_IDS = set(map(int, os.getenv("ALLOWED_USER_IDS", "").split(",")))

TOP_TOKENS = [
    "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "TRXUSDT", "SHIBUSDT",
    "LINKUSDT", "MATICUSDT", "DOTUSDT", "OPUSDT", "ARBUSDT", "WIFUSDT", "PEPEUSDT", "FLOKIUSDT", "TIAUSDT", "INJUSDT",
    "SEIUSDT", "NEARUSDT", "SUIUSDT", "RUNEUSDT", "FTMUSDT", "UNIUSDT", "LTCUSDT", "ETCUSDT", "RNDRUSDT", "1000SATSUSDT",
    "DYDXUSDT", "PYTHUSDT", "LDOUSDT", "GMXUSDT", "BCHUSDT", "ATOMUSDT", "ARKMUSDT", "JTOUSDT", "JUPUSDT", "ORDIUSDT",
    "BLURUSDT", "STXUSDT", "TIAUSDT", "CYBERUSDT", "GRTUSDT", "ENSUSDT", "CAKEUSDT", "MASKUSDT", "NTRNUSDT", "ZETAUSDT",
    "YGGUSDT", "WLDUSDT", "TUSDT", "SKLUSDT", "AGIXUSDT", "KASUSDT", "NKNUSDT", "MAVUSDT", "DEXEUSDT", "LINAUSDT", "SSVUSDT",
    "HOOKUSDT", "CTSIUSDT", "CELRUSDT", "CFXUSDT", "BANDUSDT", "STMXUSDT", "REEFUSDT", "MTLUSDT", "DODOUSDT", "BELUSDT",
    "VETUSDT", "ACHUSDT", "SANDUSDT", "ALICEUSDT", "PHBUSDT", "TOMOUSDT", "PROMUSDT", "XVSUSDT", "ZILUSDT", "CVCUSDT",
    "TRBUSDT", "ICXUSDT", "PERPUSDT", "BICOUSDT", "KAVAUSDT", "ILVUSDT", "ARDRUSDT", "SFPUSDT", "CKBUSDT", "STRAXUSDT",
    "DENTUSDT", "HIGHUSDT", "BADGERUSDT", "RIFUSDT", "MOVRUSDT", "OCEANUSDT", "OMGUSDT", "ANTUSDT", "SUPERUSDT", "BAKEUSDT"
]
