import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
BINANCE_API_KEY = os.getenv("BINANCE_API_KEY")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET")
ALLOWED_USER_IDS = set(map(int, os.getenv("ALLOWED_USER_IDS", "").split(",")))

# Diambil dari CoinGecko dan Binance (per Juli 2025) berdasarkan market cap & volume 1
TOP_TOKENS = [
    "BTCUSDT","ETHUSDT","USDTUSDT","XRPUSDT","BNBUSDT",
    "SOLUSDT","USDCUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT",
    "DOTUSDT","SHIBUSDT","MATICUSDT","TRXUSDT","LINKUSDT",
    "LTCUSDT","BCHUSDT","XLMUSDT","ALGOUSDT","HBARUSDT",
    "ICPUSDT","VETUSDT","FILUSDT","MANAUSDT","AXSUSDT",
    "SANDUSDT","GALAUSDT","NEARUSDT","FTMUSDT","CAKEUSDT",
    "THETAUSDT","EGLDUSDT","EOSUSDT","AAVEUSDT","COTIUSDT",
    "CHZUSDT","XTZUSDT","FTTUSDT","ENJUSDT","AXSUSDT",
    "CELRUSDT","FTMUSDT","KSMUSDT","RUNEUSDT","MOVRUSDT",
    "SUSHIUSDT","COMPUSDT","IMXUSDT","GLMUSDT","ONEUSDT",
    "IOTAUSDT","ZILUSDT","NEOUSDT","GRTUSDT","ANKRUSDT",
    "HOTUSDT","KAVAUSDT","CELOUSDT","RAYUSDT","OKBUSDT",
    "BATUSDT","SNXUSDT","XNOUSDT","RVNUSDT","QTUMUSDT",
    "WAVESUSDT","SRMUSDT","OCEANUSDT","BATUSDT","YFIUSDT",
    "KNCUSDT","BNTUSDT","MKRUSDT","USTCUSDT","STORJUSDT",
    "PAXGUSDT","ZECUSDT","DASHUSDT","DCRUSDT","ENJUSDT",
    "BALUSDT","LRCUSDT","SRMUSDT","ANKRUSDT","1INCHUSDT",
    "MINAUSDT","SXPUSDT","UMAUSDT","RNDRUSDT","ALICEUSDT",
    "TFUELUSDT","FLOKIUSDT","PEPEUSDT","TRUMPUSDT","BONKUSDT"
]
